return {
  {
    'mfussenegger/nvim-dap',
    keys = {
      { '<F5>' },
      { '<F8>' },
      { '<F1>' },
      { '<F11>' },
      { '<F2>' },
      { '<F10>' },
      { '<F3>' },
      { '<F9>' },
      { '<F7>' },
      { '<leader>b' },
      { '<leader>B' },
      { '<leader>dh', mode = { 'n', 'v' } },
      { '<leader>dp', mode = { 'n', 'v' } },
      { '<leader>dr' },
      { '<leader>dl' },
      { '<leader>du' },
    },
    dependencies = {
      'rcarriga/nvim-dap-ui',
      'nvim-neotest/nvim-nio',
      'mason-org/mason.nvim',
      'jay-babu/mason-nvim-dap.nvim',
      'ramboe/ramboe-dotnet-utils',
      'nvim-lua/plenary.nvim',
    },
    config = function() require 'kickstart.plugins.debug' end,
  },
  {
    'nvim-neotest/neotest',
    keys = {
      { '<leader>tt' },
      { '<leader>tf' },
      { '<leader>ts' },
      { '<leader>to' },
      { '<leader>dt' },
      { '<F6>' },
    },
    dependencies = {
      'citizenharris/neotest-dotnet',
      'antoinemadec/FixCursorHold.nvim',
      'nvim-lua/plenary.nvim',
      'nvim-neotest/nvim-nio',
      'mfussenegger/nvim-dap',
    },
    config = function() require 'custom.plugins.dotnet-test' end,
  },
}
